robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Lwheel-jt, Rwheel-jt, Fwheel-jt, Bwheel-jt, lidar-jt]

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


